### PR TITLE
Marking specific dates

### PR DESCRIPTION
**Pull request by ryanmasondavies**
Hi. I've added the ability to mark specific dates:

Screen Shot 2013-04-06 at 11 48 39

It's not possible to mark dates outside the minimum and maximum range, and the selected date overrides marking. In the above image, the 19th and 21st are marked.

I needed this feature for a project I'm working on, so I've added the bare essentials to get it working. It could probably be neater.

I've also added a podspec for using the forked repo with CocoaPods. Feel free to remove it when merging, or modify it for the main repo (I've included it in the pull request in the hopes you'll do the latter).

### CODE REVIEW

**Comment by ghost** [comment]
Neat. Thanks for this one!

**Comment by jaykz52** [comment]
@rdavies take a look at some of the work I've been doing in https://github.com/jaykz52/CKCalendar/tree/v1

It should make it very easy for devs using the calendar to customize how specific dates are styled based on the unique requirements of their app. Specifically `configureDateItem:forDate:` gives the dev the opportunity to change the display properties of the date before it is shown. How does this work jive with what you've done?

**Comment by ryanmasondavies** [comment]
This task could easily be handled in `configureDateItem:forDate:`, and moves the responsibility of highlighting certain cells elsewhere (it shouldn't really be handled directly by the calendar - it already does enough). Looks like a great update. There aren't many good open source libraries available, so I'm glad this one's being improved. When it's released, I'll be sure to make use of it. Thanks.

**Comment by jaykz52** [comment]
v1.0.0 allows for custom styling of any number of dates based on the needs of the developer via various CKCalendarDelegate methods that have been added.

**Pull request closed without merging**
