### PR TITLE
Small feature: disabling a set of dates

### PR DESCRIPTION
**Pull request by makotomiy**
I'd like to add a small feature where we can disable a set of dates. It could be useful for disabling holidays and such.

### CODE REVIEW

**Comment by jaykz52** [comment]
I wonder if it would be useful to "merge" this feature with min/max dates. I'm thinking a set of "disabled" date ranges. Maybe this is over-amibitious or would make the interface unclear.

The whole issue could be avoided by added an optional delegate method like `(BOOL)isDateEnabled:(NSDate *)date` and let delegates handle this altogether.

**Comment by makotomiy** [comment]
I hadn't thought about that... Using a delegate seems more reasonable to me too

**Comment by jaykz52** [comment]
It would be completely skirting the issue, but then "disabled dates" could meet everybody's needs (which we seem to be running up against).

**Comment by jaykz52** [comment]
@makotomiy this thread is a bit aged, but I've made some fairly drastic API changes to CKCalendar to make it more extensible for features like these. You can check it out an early version at https://github.com/jaykz52/CKCalendar/tree/v1. It should be possible to support the feature you mention above using the newer API.

The biggest change is the `calendar:dateItemForDate` delegate method, which allows you to customize the look and feel of each date as it is being drawn. Additionally, with optional delegate methods `willSelectDate`, `didSelectDate`, `willDeselectDate` and `didSelectDate`, you should able to make the above feature work relatively quickly based on your client code having a list of disabled dates.

If you get a chance to check it out, let me know if this fits your needs at all. Thanks.

**Comment by jaykz52** [comment]
v1.0.0 allows for this feature to be implemented by CKCalendarDelegate's `willSelectDate:` (return NO to disable)

**Pull request closed without merging**
