### PR TITLE
Size Change Delegate (very small)

### PR DESCRIPTION
**Pull request by michaelkschmidt**
Inform the delegate when the size of the view changes.  This will help in the case where the view is inside of a UIPopover and thus needs to resize it.

### CODE REVIEW

**Comment by jaykz52** [comment]
@michaelkschmidt since the protocol method is optional (which is a good idea), we should probably check that the delegate responds to that selector before calling it. If you can make that update that'd be killer.

Also, maybe including the frame is unnecessary? since you can get the frame right off of the passed calendar view? Does that seem kosher?

**Comment by michaelkschmidt** [comment]
@jaykz52 thanks for the reminder.  I changed the protocol method to - calendarDidResize:, and also tested for it before calling it.

The commit looks scary because I pulled your latest at the same time.  Let me know if I need to decouple them.

**Comment by jaykz52** [comment]
Nah, I'll only see the 1 liner probably since you merged my stuff in

**Comment by jaykz52** [comment]
Merged in #28, which has the same effect.

**Pull request closed without merging**
