### PR TITLE
Support for event dates

### PR DESCRIPTION
**Pull request by mdinacci**
Hi, in case you're interested I've added support for event dates, which are highlighted with a different background colour and added to a calendar view using `[calendar addEventAtDate:aDate]`.

Screen Shot 2013-02-19 at 10 45 16

### CODE REVIEW

**Comment by athanhcong** [comment]
Nice implementation Marco!
However, when I clicked into each date, all cell's background are changed dark gray color. You know why?

UPDATED: sorry, maybe I was wrong at something. Suddenly, it works as expected again.

**Comment by mdinacci** [comment]
Hi Cong,

I pushed a new version with a better implementation of eventAtDate, see if
you still experience the problem. If you do, I'll have a look into it.

Marco

**Comment by mdinacci** [comment]
Hi Cong,

it was actually a bug, I found it and pushed a quick fix. You may want to
pull from my repo if you experience the problem again.

Marco

**Comment by athanhcong** [comment]
Thanks Marco!
I read your fix, I did the same way too :)

**Comment by jaykz52** [comment]
Though I'm 100% sold on adopting this code wholesale, this feature along with some other feature requests that have been requested (multiple selected dates, disabled dates, etc.) are driving me to consider a more extensible system that would allow people to more easily modify the presentation of dates.

**Comment by mdinacci** [comment]
@jaykz52 a more extensible system would benefit everyone so it would be great if you have the time to work on it. Of course feel free at anytime to pull the code you may find useful from my fork.

**Comment by jaykz52** [comment]
Thanks @mdinacci. I'll probably snake some stuff off; hopefully we can make everybody happy!

**Comment by jaykz52** [comment]
@mdinacci check out what I'm working on in https://github.com/jaykz52/CKCalendar/tree/v1. It should be possible to  support the feature you mention above using the newer API.

For example, let's say you are keeping track of a list of event dates; the CKCalendarDelegate protocol method `calendar:dateItemForDate:` will get called for each date shown on the calendar (the current month showing, plus possibly some prev/next month spillover dates). In this method, you can see if the date is an event date and color it accordingly.

Check out the delegate methods in `CKCalendarDelegate`, you should have a lot of control over how the calendar can be interacted with. Note that I've broken the API significantly from 0.x versions, but it should be as easy as doing a few renames and implementing that `dateItemForDate` method I talked about above.

**Comment by mdinacci** [comment]
@jaykz52 I like the idea, it makes the calendar very flexible and customisable but it also shifts a lot of complexity on the delegate. Maybe if dateItemForDate: was optional you could offer a CKDateItem with some customizations already applied. Something like:

``` Objective-C
//CKCalendarView.m:314
if (self.delegate && [self.delegate respondsToSelector:@selector(dateItemForDate:)] {
    item = [self.delegate calendar:self dateItemForDate:date];
} else {
    item = [[CKDateItem alloc] init];
    // Now customize the item according to whether it's selected or represents the current day etc...similar to
   // what is done in the master branch.
}
```

**Comment by jaykz52** [comment]
I agree with your concerns. I think we can mitigate this by introducing a `CKCalendarDefaultDelegate` class (or something along those lines) that can basically return CKCalendar's to the functionality prior to this branch without fuzzing the lines beween the delegate's responsibilities and the calendar's itself.

**Comment by jaykz52** [comment]
Another option I'm a little more okay with would be to make `dateItemForDate` optional, but change it so that the dateItem is passed in as well, the delegate could choose to modify it's properties if it so chose to.

**Comment by mdinacci** [comment]
Given the features I need, I'll be happier with your second option. 
Oh, I just noticed you added a `calendar:configureDateItem:forDate` method. That's fine with me, thanks.

**Pull request closed without merging**
