### PR TITLE
The calendar can be set to take a fixed amount of vertical space

### PR DESCRIPTION
**Pull request by akikoskinen**
Months need 4-6 rows (weeks) to be shown. This setting chooses whether the height of the calendar view should be adjusted according to the needed rows (the current behavior, and still the default) or should it always take the maximum height, i.e. space for six weeks.

There are two commits in this pull request put only the second one is relevant. The first commit is part of pull request 19.

### CODE REVIEW

**Comment by akikoskinen** [comment]
Any opinions/comments/ideas about this pull request? Is it good, bad or something else? Now it just seems to be in a limbo state. Would be nice that it would move to some direction - be it the master branch or dustbin.

**Comment by jaykz52** [comment]
No, I'm definitely interested in the code. I apologize for the delay; Truthfully, I've been side tracked on some other projects and this commit was simply larger than the others you've submitted, so I want to make sure I have time grok everything. I'll make a point to look at it at the beginning of the coming week (I'm going to be away from my computer this weekend). Thanks for your contributions!

**Comment by akikoskinen** [comment]
Good stuff. Note that as said in the original message **only the second commit** is part of this pull request.

The first commit was part of another pull request that has been already merged. The pull request ended up being like this because of the way I made the commits (on top of each other). Perhaps it wasn't the best way...

**Comment by jaykz52** [comment]
Np; I'll cherry pick that shit out.

**Pull request merged**
